dist: focal
os: linux

jobs:
  include:
    - language: c
      compiler: gcc

      before_install:
        - cd src/hw-1
        - sudo apt-get -y install libgtk-3-dev
      addons:
        apt:
          update: true
      script: 
        - make


    - language: python
      python: "3.8"

      install:
        - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
            wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
          else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          fi
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda config --append channels conda-forge # for pygraphblas
        - conda info -a

        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pygraphblas scipy networkx
        - conda activate test-environment
      
      script:
        - python -m pytest

