dist: focal
os: linux

jobs:
  include:
    - language: c
      compiler: gcc

      before_install:
        - cd src/hw-1
        - sudo apt-get -y install libgtk-3-dev
      addons:
        apt:
          update: true
      script: 
        - make

